/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dsi2021.aula8;

/**
 *
 * @author diegomoraes
 */
public class Exemplo2 extends javax.swing.JFrame {

    /**
     * Creates new form Exemplo1
     */
    public Exemplo2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbGrupo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtValor1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtValor2 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtResultado = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtOpera = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        rbSoma = new javax.swing.JRadioButton();
        rbSubt = new javax.swing.JRadioButton();
        rbMulti = new javax.swing.JRadioButton();
        rbDiv = new javax.swing.JRadioButton();
        btnCalcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(new java.awt.GridLayout(2, 1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Digite o primeiro valor:");
        jPanel1.add(jLabel2);
        jPanel1.add(txtValor1);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Digite o segundo valor:");
        jPanel1.add(jLabel3);
        jPanel1.add(txtValor2);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setText("Digite o nome:");
        jPanel2.add(jLabel1);
        jPanel2.add(jTextField1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(102, 255, 102));
        jPanel3.setPreferredSize(new java.awt.Dimension(447, 80));
        jPanel3.setLayout(new java.awt.GridLayout(1, 4));

        jLabel4.setText("Resultado:");
        jPanel3.add(jLabel4);

        txtResultado.setText("jLabel5");
        jPanel3.add(txtResultado);

        jLabel6.setText("Operação:");
        jPanel3.add(jLabel6);

        txtOpera.setText("jLabel7");
        jPanel3.add(txtOpera);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel4.setLayout(new java.awt.GridLayout(5, 1));

        rbGrupo.add(rbSoma);
        rbSoma.setText("Soma");
        rbSoma.setActionCommand("r1");
        jPanel4.add(rbSoma);

        rbGrupo.add(rbSubt);
        rbSubt.setText("Subtração");
        rbSubt.setActionCommand("r2");
        jPanel4.add(rbSubt);

        rbGrupo.add(rbMulti);
        rbMulti.setText("Multiplicação");
        rbMulti.setActionCommand("r3");
        jPanel4.add(rbMulti);

        rbGrupo.add(rbDiv);
        rbDiv.setText("Divisão");
        rbDiv.setActionCommand("r4");
        jPanel4.add(rbDiv);

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        jPanel4.add(btnCalcular);

        getContentPane().add(jPanel4, java.awt.BorderLayout.LINE_END);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
       
        String opt = rbGrupo.getSelection().getActionCommand();
        
        double v1, v2, resultado;
        
        v1 = Double.parseDouble(txtValor1.getText());
        v2 = Double.parseDouble(txtValor2.getText());
        
        switch(opt){
            
            case "r1":
                resultado = v1+v2;
                txtResultado.setText(String.valueOf(String.format("%.2f", resultado)));
                txtOpera.setText("Soma");
                break;
                
             case "r2":
                resultado = v1-v2;
                txtResultado.setText(String.valueOf(String.format("%.2f", resultado)));
                txtOpera.setText("Subtração");
                break;
            
             case "r3":
                resultado = v1*v2;
                txtResultado.setText(String.valueOf(String.format("%.2f", resultado)));
                txtOpera.setText("Multiplicação");
                break;
             
             case "r4":
                resultado = v1/v2;
                txtResultado.setText(String.valueOf(String.format("%.2f", resultado)));
                txtOpera.setText("Divisão");
                break;
                
             default: 
                txtOpera.setText("Nenhuma operação");
                txtResultado.setText("0");
            
            
        }
        
        
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exemplo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exemplo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exemplo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exemplo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exemplo2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton rbDiv;
    private javax.swing.ButtonGroup rbGrupo;
    private javax.swing.JRadioButton rbMulti;
    private javax.swing.JRadioButton rbSoma;
    private javax.swing.JRadioButton rbSubt;
    private javax.swing.JLabel txtOpera;
    private javax.swing.JLabel txtResultado;
    private javax.swing.JTextField txtValor1;
    private javax.swing.JTextField txtValor2;
    // End of variables declaration//GEN-END:variables
}
